const express = require("express");
const router = express.Router();
const userRouter = require("./userRouter");
const resetRouter = require("./reset");
const matchRouter = require("./matchRouter");
const messageRouter = require("./messageRouter");
const userMatchesRouter = require("./userMatchesRouter");
const oneUserAllMatches = require("./helper");
const allUsers = require("./userHelper");
const userPart = require("./userPart");
const noMatches = require("./matchesNo");
const matchesPart = require("./matchesPart");
const usersMatch = require("./matchUsersRouter");
const teamRouter = require("./teamRouter");
const tournamentRouter = require("./tournamentRouter");
const tournamentTeamsRouter = require("./tournamentTeamsRouter");
const helperTourneyTeamsRouter = require("./helperTourneyTeamsRouter");
const tournamentMatch = require("./tournamentMatchRouter");
const statsHelper = require("./statsHelper");

router.use("/user", userRouter);
router.use("/reset", resetRouter);
router.use("/match", matchRouter);
router.use("/msg", messageRouter);
router.use("/ums", userMatchesRouter);
router.use("/one", oneUserAllMatches);
router.use("/all", allUsers);
router.use("/part", userPart);
router.use("/no", noMatches);
router.use("/nm", matchesPart);
router.use("/usersOne", usersMatch);
router.use("/team", teamRouter);
router.use("/tournament", tournamentRouter);
router.use("/tourteams", tournamentTeamsRouter);
router.use("/tourhelper", helperTourneyTeamsRouter);
router.use("/tourmatch", tournamentMatch);
router.use("/stats", statsHelper);

module.exports = router;
